import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export const LANGUAGES = [
  { code: 'en', label: 'English (IN)' },
  { code: 'hi', label: 'Hindi (हिन्दी)' },
  { code: 'ta', label: 'Tamil (தமிழ்)' },
  { code: 'te', label: 'Telugu (తెలుగు)' },
  { code: 'kn', label: 'Kannada (ಕನ್ನಡ)' },
]

export const TRANSLATIONS = {
  en: {
    settings: "Settings",
    editProfile: "Edit Profile",
    deliveryAddresses: "Delivery Addresses",
    language: "Language",
    generalSettings: "General Settings",
    security: "Security",
    twoFactor: "Two-Factor Authentication",
    savedCards: "Saved Cards",
    passwordLogin: "Active Sessions",
    dangerZone: "Danger Zone",
    deleteAccount: "Delete Account",
    appearance: "Appearance",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    searchPlaceholder: "Search for fresh fruits, vegetables, & Mithila specials...",
    home: "Home",
    categories: "Categories",
    cart: "Cart",
    wishlist: "Wishlist",
    profile: "Profile",
    referEarn: "Refer & Earn",
    inviteFriends: "Invite Friends",
    tenMinMagic: "Experience the 30-minute magic!",
    referralPromo: "Get 3 FREE deliveries!",
    accountSummary: "Account Summary",
    memberSince: "Member Since",
    totalOrders: "Total Orders",
    ozoCoins: "Ozo Coins",
    logout: "Logout Account",
    saveChanges: "Save Changes",
    editingProfile: "Editing Profile",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    emailAddress: "Email Address",
    managePreferences: "Manage your account and preferences",
    welcomeBack: "Welcome Back!",
    myOrders: "My Orders",
    savedAddresses: "Saved Addresses",
    paymentMethods: "Payment Methods",
    cancel: "Cancel",
    notifications: "Notifications",
    editPersonalInfo: "Edit Personal Information",
    ongoingOrder: "Ongoing Order",
    trackCurrentDelivery: "Track your current delivery",
    viewDetails: "View Details",
    primaryAddress: "Primary Address",
    setDeliveryAddress: "Set your delivery address",
    manageAddresses: "Manage Addresses",
    customizeAvatar: "Customize Avatar",
    avatarSubtitle: "Choose a fun preset character or upload your own photo.",
    uploadCustomImage: "Upload Custom Image",
    chooseImageFile: "Choose image file",
    uploading: "Uploading...",
    selectPreset: "Select Preset Character",
    removeCustomAvatar: "Remove Custom Avatar",
    checkout: "Checkout",
    payment_method: "Payment Method",
    banner1Title: "Fresh Organic Vegetables",
    banner1Subtitle: "Farm-fresh arrivals delivered in 30 mins",
    banner1Tagline: "Farm Fresh",
    banner2Title: "Fresh & Juicy Fruits",
    banner2Subtitle: "Premium quality fruits loaded with vitamins",
    banner2Tagline: "Premium Fruits",
    banner3Title: "Authentic Mithila Delights",
    banner3Subtitle: "Traditional home-made pickles, sweets, & special treats",
    banner3Tagline: "Mithila Special",
    freeDeliveryTitle: "Free Delivery",
    fastDeliveryTitle: "Fast Delivery",
    freeDeliveryAbove: "On orders above ₹{amount}",
    fastDeliveryBaseFee: "Base fee: ₹{amount}",
  },
  hi: {
    settings: "सेटिंग्स",
    editProfile: "प्रोफ़ाइल संपादित करें",
    deliveryAddresses: "वितरण पता",
    language: "भाषा",
    generalSettings: "सामान्य सेटिंग्स",
    security: "सुरक्षा",
    twoFactor: "टू-फैक्टर प्रमाणीकरण",
    savedCards: "सहेजे गए कार्ड",
    passwordLogin: "सक्रिय सेशन्स",
    dangerZone: "खतरे का क्षेत्र",
    deleteAccount: "खाता हटाएं",
    appearance: "दिखावट",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    searchPlaceholder: "ताजे फल, सब्जियां और मिथिला विशेषताएँ खोजें...",
    home: "होम",
    categories: "श्रेणियाँ",
    cart: "कार्ट",
    wishlist: "इच्छा-सूची",
    profile: "प्रोफ़ाइल",
    referEarn: "रेफर करें और कमाएं",
    inviteFriends: "मित्रों को आमंत्रित करें",
    tenMinMagic: "30 मिनट के जादू का अनुभव करें!",
    referralPromo: "3 मुफ्त डिलीवरी पाएं!",
    accountSummary: "खाता विवरण",
    memberSince: "सदस्यता की शुरुआत",
    totalOrders: "कुल ऑर्डर्स",
    ozoCoins: "ओजो कॉइन्स",
    logout: "खाता लॉगआउट करें",
    saveChanges: "बदलाव सहेजें",
    editingProfile: "प्रोफ़ाइल संपादन",
    fullName: "पूरा नाम",
    phoneNumber: "फ़ोन नंबर",
    emailAddress: "ईमेल पता",
    managePreferences: "अपने खाते और प्राथमिकताओं को प्रबंधित करें",
    welcomeBack: "वापसी पर स्वागत है!",
    myOrders: "मेरे ऑर्डर्स",
    savedAddresses: "सहेजे गए पते",
    paymentMethods: "भुगतान की विधियां",
    cancel: "रद्द करें",
    notifications: "सूचनाएं",
    editPersonalInfo: "व्यक्तिगत जानकारी संपादित करें",
    ongoingOrder: "सक्रिय ऑर्डर",
    trackCurrentDelivery: "अपने वर्तमान ऑर्डर को ट्रैक करें",
    viewDetails: "विवरण देखें",
    primaryAddress: "प्राथमिक पता",
    setDeliveryAddress: "अपना वितरण पता सेट करें",
    manageAddresses: "पते प्रबंधित करें",
    customizeAvatar: "अवतार कस्टमाइज़ करें",
    avatarSubtitle: "एक मज़ेदार प्रीसेट चरित्र चुनें या अपनी फ़ोटो अपलोड करें।",
    uploadCustomImage: "कस्टम छवि अपलोड करें",
    chooseImageFile: "छवि फ़ाइल चुनें",
    uploading: "अपलोड हो रहा है...",
    selectPreset: "प्रीसेट चरित्र चुनें",
    removeCustomAvatar: "कस्टम अवतार हटाएं",
    checkout: "चेकआउट",
    payment_method: "भुगतान की विधि",
    banner1Title: "ताजी जैविक सब्जियां",
    banner1Subtitle: "खेत से ताजी सब्जियां 30 मिनट में डिलीवर",
    banner1Tagline: "ताजी सब्जियां",
    banner2Title: "ताजे और रसीले फल",
    banner2Subtitle: "विटामिन से भरपूर प्रीमियम गुणवत्ता वाले फल",
    banner2Tagline: "प्रीमियम फल",
    banner3Title: "प्रामाणिक मिथिला व्यंजन",
    banner3Subtitle: "पारंपरिक घरेलू अचार, मिठाइयाँ और विशेष व्यंजन",
    banner3Tagline: "मिथिला स्पेशल",
    freeDeliveryTitle: "मुफ्त डिलीवरी",
    fastDeliveryTitle: "तेज डिलीवरी",
    freeDeliveryAbove: "₹{amount} से अधिक के ऑर्डर पर मुफ्त",
    fastDeliveryBaseFee: "आधार शुल्क: ₹{amount}",
  },
  ta: {
    settings: "அமைப்புகள்",
    editProfile: "சுயவிவரத்தை திருத்து",
    deliveryAddresses: "டெலிவரி முகவரிகள்",
    language: "மொழி",
    generalSettings: "பொதுவான அமைப்புகள்",
    security: "பாதுகாப்பு",
    twoFactor: "இரு காரணி அங்கீகாரம்",
    savedCards: "சேமிக்கப்பட்ட கார்டுகள்",
    passwordLogin: "செயலில் உள்ள அமர்வுகள்",
    dangerZone: "அபாய பகுதி",
    deleteAccount: "கணக்கை நீக்கு",
    appearance: "தோற்றம்",
    lightMode: "ஒளி பயன்முறை",
    darkMode: "இருண்ட பயன்முறை",
    searchPlaceholder: "புதிய பழங்கள், காய்கறிகள் மற்றும் ஸ்பெஷல்களைத் தேடுங்கள்...",
    home: "முகப்பு",
    categories: "வகைகள்",
    cart: "வண்டி",
    wishlist: "விருப்பப்பட்டியல்",
    profile: "சுயவிவரம்",
    referEarn: "பரிந்துரைத்து சம்பாதிக்கவும்",
    inviteFriends: "நண்பர்களை அழைக்கவும்",
    tenMinMagic: "30 நிமிட மேஜிக்கை அனுபவிக்கவும்!",
    referralPromo: "3 இலவச டெలిவரிகளைப் பெறுங்கள்!",
    accountSummary: "கணக்கு சுருக்கம்",
    memberSince: "உறுப்பினர் காலம்",
    totalOrders: "மொத்த ஆர்டர்கள்",
    ozoCoins: "ஓசோ காயின்கள்",
    logout: "வெளியேறு",
    saveChanges: "மாற்றங்களைச் சேமி",
    editingProfile: "சுயவிவரத்தைத் திருத்துதல்",
    fullName: "முழு பெயர்",
    phoneNumber: "தொலைபேசி எண்",
    emailAddress: "மின்னஞ்சல் முகவரி",
    managePreferences: "உங்கள் கணக்கு மற்றும் விருப்பங்களை நிர்வகிக்கவும்",
    welcomeBack: "மீண்டும் வருக!",
    myOrders: "என் ஆர்டர்கள்",
    savedAddresses: "சேமிக்கப்பட்ட முகவரிகள்",
    paymentMethods: "கொடுப்பனவு முறைகள்",
    cancel: "ரத்து செய்",
    notifications: "அறிவிப்புகள்",
    editPersonalInfo: "தனிப்பட்ட தகவலைத் திருத்து",
    ongoingOrder: "தற்போதைய ஆர்டர்",
    trackCurrentDelivery: "உங்கள் தற்போதைய விநியோகத்தைக் கண்காணிக்கவும்",
    viewDetails: "விவரங்களைக் காண்க",
    primaryAddress: "முதன்மை முகவரி",
    setDeliveryAddress: "உங்கள் டெலிவரி முகவரியை அமைக்கவும்",
    manageAddresses: "முகவரிகளை நிர்வகி",
    customizeAvatar: "சுயவிவரப் படத்தை மாற்றவும்",
    avatarSubtitle: "ஒரு வேடிக்கையான முன்னமைக்கப்பட்ட கதாபாத்திரத்தைத் தேர்வு செய்யவும் அல்லது உங்கள் சொந்த புகைப்படத்தைப் பதிவேற்றவும்.",
    uploadCustomImage: "தனிப்பயன் படத்தை பதிவேற்றவும்",
    chooseImageFile: "படக் கோப்பைத் தேர்ந்தெடுக்கவும்",
    uploading: "பதிவேற்றப்படுகிறது...",
    selectPreset: "முன்னமைக்கப்பட்ட கதாபாத்திரத்தைத் தேர்ந்தெடுக்கவும்",
    removeCustomAvatar: "தனிப்பயன் அவதாரத்தை நீக்கு",
    checkout: "செக்அவுட்",
    payment_method: "கொடுப்பனவு முறை",
    banner1Title: "புதிய ஆர்கானிக் காய்கறிகள்",
    banner1Subtitle: "30 நிமிடங்களில் வழங்கப்படும் பண்ணை-புதிய காய்கறிகள்",
    banner1Tagline: "பண்ணை புதியது",
    banner2Title: "புதிய மற்றும் ஜூசி பழங்கள்",
    banner2Subtitle: "வைட்டமின்கள் நிறைந்த பிரೀமியம் தரமான பழங்கள்",
    banner2Tagline: "பிரೀமியம் பழங்கள்",
    banner3Title: "அசல் மிதிலา உணவுகள்",
    banner3Subtitle: "பாரம்பரிய வீட்டில் தயாரித்த ஊறுகாய், இனிப்புகள் மற்றும் சிறப்பு உணவுகள்",
    banner3Tagline: "மிதிலா சிறப்பு",
    freeDeliveryTitle: "இலவச டெலிவரி",
    fastDeliveryTitle: "வேகமான டெலிவரி",
    freeDeliveryAbove: "₹{amount}க்கு மேலான ஆர்டர்களுக்கு",
    fastDeliveryBaseFee: "அடிப்படை கட்டணம்: ₹{amount}",
  },
  te: {
    settings: "సెట్టింగులు",
    editProfile: "ప్రొఫైల్ సవరించండి",
    deliveryAddresses: "డెలివరీ చిరునామాలు",
    language: "భాష",
    generalSettings: "సాధారణ సెట్టింగులు",
    security: "భద్రత",
    twoFactor: "ద్వి-కారక ధృవీకరణ",
    savedCards: "సేవ్ చేసిన కార్డులు",
    passwordLogin: "యాక్టివ్ సెషన్స్",
    dangerZone: "ఆందోళన ప్రాంతం",
    deleteAccount: "ఖాతాను తొలగించండి",
    appearance: "రూపం",
    lightMode: "లైట్ మోడ్",
    darkMode: "డార్క్ మోడ్",
    searchPlaceholder: "తాజా పండ్లు, కూరగాయలు మరియు ప్రత్యేకతల కోసం వెతకండి...",
    home: "హోమ్",
    categories: "వర్గాలు",
    cart: "కార్ట్",
    wishlist: "విష్ లిస్ట్",
    profile: "ప్రొఫైల్",
    referEarn: "రిఫర్ చేయండి & సంపాదించండి",
    inviteFriends: "స్నేహితులను ఆహ్వానించండి",
    tenMinMagic: "30 నిమిషాల మ్యాజిక్‌ను అనుభవించండి!",
    referralPromo: "3 ఉచిత డెలివరీలు పొందండి!",
    accountSummary: "ఖాతా సారాంశం",
    memberSince: "సభ్యునిగా చేరినది",
    totalOrders: "మొత్తం ఆర్డర్లు",
    ozoCoins: "ఓజో కాయిన్స్",
    logout: "లాగ్ అవుట్",
    saveChanges: "మార్పులను సేవ్ చేయి",
    editingProfile: "ప్రొఫైల్ సవరణ",
    fullName: "పూర్తి పేరు",
    phoneNumber: "ఫోన్ నంబర్",
    emailAddress: "ఈమెయిల్ చిరునామా",
    managePreferences: "మీ ఖాతా మరియు ప్రాధాన్యతలను నిర్వహించండి",
    welcomeBack: "తిరిగి స్వాగతం!",
    myOrders: "నా ఆర్డర్లు",
    savedAddresses: "సేవ్ చేసిన చిరునామాలు",
    paymentMethods: "చెల్లింపు పద్ధతులు",
    cancel: "రద్దు చేయి",
    notifications: "నోటిఫికేషన్లు",
    editPersonalInfo: "వ్యక్తిగత సమాచారాన్ని సవరించండి",
    ongoingOrder: "కొనసాగుతున్న ఆర్డర్",
    trackCurrentDelivery: "మీ ప్రస్తుత డెలివరీని ట్రాక్ చేయండి",
    viewDetails: "వివరాలు వీక్షించండి",
    primaryAddress: "ప్రాథమిక చిరునామా",
    setDeliveryAddress: "మీ డెలివరీ చిరునామాను సెట్ చేయండి",
    manageAddresses: "చిరునామాలను నిర్వహించండి",
    customizeAvatar: "అవతార్‌ను అనుకూలీకరించండి",
    avatarSubtitle: "సరదా ప్రీసెట్ అక్షరాన్ని ఎంచుకోండి లేదా మీ స్వంత ఫోటోను అప్‌లోడ్ చేయండి.",
    uploadCustomImage: "కస్టమ్ చిత్రాన్ని అప్‌లోడ్ చేయండి",
    chooseImageFile: "చిత్ర ఫైల్‌ను ఎంచుకోండి",
    uploading: "అప్‌లోడ్ అవుతోంది...",
    selectPreset: "ప్రీసెట్ అక్షరాన్ని ఎంచుకోండి",
    removeCustomAvatar: "కస్టమ్ అవతార్‌ను తీసివేయండి",
    checkout: "చెక్అవుట్",
    payment_method: "చెల్లింపు పద్ధతి",
    banner1Title: "తాజా సేంద్రీయ కూరగాయలు",
    banner1Subtitle: "30 నిమిషాల్లో డెలివరీ చేయబడే తాజా కూరగాయలు",
    banner1Tagline: "తాజా కూరగాయలు",
    banner2Title: "తాజా మరియు జ్యుసి పండ్లు",
    banner2Subtitle: "విటమిన్లు నిండిన ప్రీమియం నాణ్యత పండ్లు",
    banner2Tagline: "ప్రీమియం పండ్లు",
    banner3Title: "అథెంటిక్ మిథిలా రుచులు",
    banner3Subtitle: "సాంప్రదాయ ఇంట్లో తయారుచేసిన పచ్చళ్లు, స్వీట్లు & ప్రత్యేక వంటకాలు",
    banner3Tagline: "మిథిలా స్పెషల్",
    freeDeliveryTitle: "ఉచిత డెలివరీ",
    fastDeliveryTitle: "వేగవంతమైన డెలివరీ",
    freeDeliveryAbove: "₹{amount} కంటే ఎక్కువ ఆర్డర్‌లపై",
    fastDeliveryBaseFee: "బేస్ రుసుము: ₹{amount}",
  },
  kn: {
    settings: "ಸಂಯೋಜನೆಗಳು",
    editProfile: "ಪ್ರೊಫೈಲ್ ತಿದ್ದಿ",
    deliveryAddresses: "ಡೆಲಿವರಿ ವಿಳಾಸಗಳು",
    language: "ಭಾಷೆ",
    generalSettings: "ಸಾಮಾನ್ಯ ಸೆಟ್ಟಿಂಗ್ಸ್",
    security: "ಭದ್ರತೆ",
    twoFactor: "ದ್ವಿ-ಅಂಶ ದೃಢೀಕರಣ",
    savedCards: "ಉಳಿಸಿದ ಕಾರ್ಡ್‌ಗಳು",
    passwordLogin: "ಸಕ್ರಿಯ ಸೆಷನ್‌ಗಳು",
    dangerZone: "ಡೇಂಜರ್ ಝೋನ್",
    deleteAccount: "ಖಾತೆಯನ್ನು ಅಳಿಸಿ",
    appearance: "ರೂಪ",
    lightMode: "ಲೈಟ್ ಮೋಡ್",
    darkMode: "ಡಾರ್ಕ್ ಮೋಡ್",
    searchPlaceholder: "ತಾಜಾ ಹಣ್ಣುಗಳು, ತರಕಾರಿಗಳು ಮತ್ತು ವಿಶೇಷತೆಗಳಿಗಾಗಿ ಹುಡುಕಿ...",
    home: "ಹೋಮ್",
    categories: "ವರ್ಗಗಳು",
    cart: "ಕಾರ್ಟ್",
    wishlist: "ವಿಶ್ ಲಿಸ್ಟ್",
    profile: "ಪ್ರೊಫೈಲ್",
    referEarn: "ರೆಫರ್ ಮಾಡಿ ಮತ್ತು ಸಂಪಾದಿಸಿ",
    inviteFriends: "ಸ್ನೇಹಿತರನ್ನು ಆಹ್ವಾನಿಸಿ",
    tenMinMagic: "30 ನಿಮಿಷಗಳ ಮ್ಯಾಜಿಕ್ ಅನುಭವಿಸಿ!",
    referralPromo: "3 ಉಚಿತ ಡೆಲಿವರಿ ಪಡೆಯಿರಿ!",
    accountSummary: "ಖಾತೆಯ ಸಾರಾಂಶ",
    memberSince: "ಸದಸ್ಯರಾದಂದಿನಿಂದ",
    totalOrders: "ಒಟ್ಟು ಆರ್ಡರ್ಸ್",
    ozoCoins: "ಓಜೋ ಕಾಯಿನ್ಸ್",
    logout: "ಖಾತೆಯಿಂದ ನಿರ್ಗಮಿಸಿ",
    saveChanges: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
    editingProfile: "ಪ್ರೊಫೈಲ್ ಎಡಿಟಿಂಗ್",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    phoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆ",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    managePreferences: "ನಿಮ್ಮ ಖಾತೆ ಮತ್ತು ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    welcomeBack: "ಮರಳಿ ಸ್ವಾಗತ!",
    myOrders: "ನನ್ನ ಆರ್ಡರ್ಸ್",
    savedAddresses: "ಉಳಿಸಿದ ವಿಳಾಸಗಳು",
    paymentMethods: "ಪಾವತಿ ವಿಧಾನಗಳು",
    cancel: "ರದ್ದುಗೊಳಿಸಿ",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    editPersonalInfo: "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿಯನ್ನು ತಿದ್ದಿ",
    ongoingOrder: "ನಡೆಯುತ್ತಿರುವ ಆರ್ಡರ್",
    trackCurrentDelivery: "ನಿಮ್ಮ ಪ್ರಸ್ತುತ ವಿತರಣೆಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    viewDetails: "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    primaryAddress: "ಪ್ರಾಥಮಿಕ ವಿಳಾಸ",
    setDeliveryAddress: "ನಿಮ್ಮ ವಿತರಣಾ ವಿಳಾಸವನ್ನು ಹೊಂದಿಸಿ",
    manageAddresses: "ವಿಳಾಸಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    customizeAvatar: "ಅವತಾರವನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಿ",
    avatarSubtitle: "ಮೋಜಿನ ಪ್ರಿಸೆಟ್ ಪಾತ್ರವನ್ನು ಆರಿಸಿ ಅಥವಾ ನಿಮ್ಮ ಸ್ವಂತ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    uploadCustomImage: "ಕಸ್ಟಮ್ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    chooseImageFile: "ಚಿತ್ರದ ಫೈಲ್ ಅನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    uploading: "ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    selectPreset: "ಪ್ರಿಸೆಟ್ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    removeCustomAvatar: "ಕಸ್ಟಮ್ ಅವತಾರವನ್ನು ತೆಗೆದುಹಾಕಿ",
    checkout: "ಚೆಕ್ಔಟ್",
    payment_method: "ಪಾವತಿ ವಿಧಾನ",
    banner1Title: "ತಾಜಾ ಸಾವಯವ ತರಕಾರಿಗಳು",
    banner1Subtitle: "30 ನಿಮಿಷಗಳಲ್ಲಿ ತಲುಪಿಸುವ ತಾಜಾ ತರಕಾರಿಗಳು",
    banner1Tagline: "ಫಾರ್ಮ್ ತಾಜಾ",
    banner2Title: "ತಾಜಾ ಮತ್ತು ರಸಭರಿत ಹಣ್ಣುಗಳು",
    banner2Subtitle: "ವಿಟಮಿನ್‌ಗಳಿಂದ ಕೂಡಿದ ಪ್ರೀಮಿಯಂ ಗುಣಮಟ್ಟದ ಹಣ್ಣುಗಳು",
    banner2Tagline: "ಪ್ರೀಮಿಯಂ ಹಣ್ಣುಗಳು",
    banner3Title: "ಅಪ್ಪಟ ಮಿಥಿಲಾ ವಿಶೇಷತೆಗಳು",
    banner3Subtitle: "ಸಾಂಪ್ರದಾಯಿಕ ಮನೆಯಲ್ಲಿ ತಯಾರಿಸಿದ ಉಪ್ಪಿನಕಾಯಿ, ಸಿಹಿತಿಂಡಿಗಳು ಮತ್ತು ವಿಶೇಷ ತಿನಿಸುಗಳು",
    banner3Tagline: "ಮಿಥಿಲಾ ಸ್ಪೆಷಲ್",
    freeDeliveryTitle: "ಉಚಿತ ಡೆಲಿವರಿ",
    fastDeliveryTitle: "ವೇಗದ ಡೆಲಿವರಿ",
    freeDeliveryAbove: "₹{amount} ಗಿಂತ ಹೆಚ್ಚಿನ ಆರ್ಡರ್‌ಗಳ ಮೇಲೆ",
    fastDeliveryBaseFee: "ಮೂಲ ಶುಲ್ಕ: ₹{amount}",
  },
}

export const useLanguageStore = create(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (code) => set({ language: code }),
      t: (key) => {
        const lang = get().language || 'en'
        return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en']?.[key] || key
      },
      getCurrentLanguageLabel: () => {
        const lang = get().language || 'en'
        return LANGUAGES.find(l => l.code === lang)?.label || 'English (IN)'
      }
    }),
    {
      name: 'ozo-language-storage',
    }
  )
)
